const exampleModule = {
  module: "MMM-DisneyWaitTimes",
  header: "Magic Kingdom - Disneyland",
  position: "top_left",
  config: {
    park: {
      name: "Magic Kingdom - Disneyland",
      rides: [
        "Alice in Wonderland",
        "Astro Orbitor",
        "Autopia",
        "Big Thunder Mountain Railroad",
        "Buzz Lightyear Astro Blasters",
        "Casey Jr. Circus Train",
        "Davy Crockett's Explorer Canoes",
        "Disneyland Monorail",
        "Disneyland Railroad - Tomorrowland Station",
        "Dumbo the Flying Elephant",
        "Encounter the Dark Side at Star Wars Launch Bay",
        "Fantasmic!",
        "Finding Nemo Submarine Voyage",
        "Gadget's Go Coaster",
        "Haunted Mansion",
        "Indiana Jones™ Adventure",
        "it's a small world",
        "Jungle Cruise",
        "King Arthur Carrousel",
        "Mad Tea Party",
        "Mark Twain Riverboat",
        "Matterhorn Bobsleds",
        "Meet Disney Princesses at Royal Hall",
        "Meet the Resistance at Star Wars Launch Bay",
        "Meet Tinker Bell at Pixie Hollow",
        "Mickey and the Magical Map",
        "Mickey's House and Meet Mickey",
        "Millennium Falcon: Smugglers Run",
        "Mr. Toad's Wild Ride",
        "Peter Pan's Flight",
        "Pinocchio's Daring Journey",
        "Pirate's Lair on Tom Sawyer Island",
        "Pirates of the Caribbean",
        "Roger Rabbit's Car Toon Spin",
        "Sailing Ship Columbia",
        "Snow White's Scary Adventures",
        "Space Mountain",
        "Splash Mountain",
        "Star Tours – The Adventures Continue",
        "Star Wars Launch Bay",
        "Storybook Land Canal Boats",
        "Tarzan's Treehouse™",
        "The Disneyland Story presenting Great Moments with Mr. Lincoln",
        "The Many Adventures of Winnie the Pooh",
        "Walt Disney's Enchanted Tiki Room"
      ]
    }
  }
};
