const exampleModule = {
  module: "MMM-DisneyWaitTimes",
  header: "Magic Kingdom - Disneyland",
  position: "top_left",
  config: {
    park: {
      name: "Magic Kingdom - Disneyland",
      rides: [
        "Alice in Wonderland",
        "Astro Orbitor",
        "Autopia",
        "Big Thunder Mountain Railroad",
        "Buzz Lightyear Astro Blasters",
        "Casey Jr. Circus Train",
        "Chip 'n Dale Treehouse",
        "Chip 'n' Dale's GADGETcoaster",
        "Davy Crockett's Explorer Canoes",
        "Disneyland Monorail",
        "Disneyland Railroad",
        "Dumbo the Flying Elephant",
        "Finding Nemo Submarine Voyage",
        "Goofy's How-to-Play Yard",
        "Haunted Mansion",
        "Indiana Jones™ Adventure",
        "it's a small world",
        "Jungle Cruise",
        "King Arthur Carrousel",
        "Mad Tea Party",
        "Mark Twain Riverboat",
        "Matterhorn Bobsleds",
        "Mickey & Minnie's Runaway Railway",
        "Millennium Falcon: Smugglers Run",
        "Mr. Toad's Wild Ride",
        "Peter Pan's Flight",
        "Pinocchio's Daring Journey",
        "Pirate's Lair on Tom Sawyer Island",
        "Pirates of the Caribbean",
        "Roger Rabbit's Car Toon Spin",
        "Sailing Ship Columbia",
        "Sleeping Beauty Castle Walkthrough",
        "Snow White's Enchanted Wish",
        "Space Mountain",
        "Star Tours - The Adventures Continue",
        "Star Wars Launch Bay",
        "Star Wars: Rise of the Resistance",
        "Storybook Land Canal Boats",
        "Tarzan's Treehouse™",
        "The Disneyland Story presenting Great Moments with Mr. Lincoln",
        "The Many Adventures of Winnie the Pooh",
        "Walt Disney's Enchanted Tiki Room"
      ]
    }
  }
};
