const exampleModule = {
  module: "MMM-DisneyWaitTimes",
  header: "Magic Kingdom - Disneyland Paris",
  position: "top_left",
  config: {
    park: {
      name: "Magic Kingdom - Disneyland Paris",
      rides: [
        "Adventure Isle",
        "Alice's Curious Labyrinth",
        "Autopia®",
        "Big Thunder Mountain",
        "Blanche-Neige et les Sept Nains®",
        "Buzz Lightyear Laser Blast",
        "Casey Jr. – le Petit Train du Cirque",
        "Discovery Arcade",
        "Disneyland Railroad Discoveryland Station",
        "Disneyland Railroad Fantasyland Station",
        "Disneyland Railroad Frontierland Depot",
        "Disneyland Railroad Main Street Station",
        "Dumbo the Flying Elephant",
        "Frontierland Playground",
        "Horse-Drawn Streetcars",
        "Indiana Jones™ and the Temple of Peril",
        "it's a small world'",
        "La Cabane des Robinson",
        "La Galerie de la Belle au Bois Dormant",
        "La Tanière du Dragon",
        "Le Carrousel de Lancelot",
        "Le Passage Enchanté d'Aladdin",
        "Le Pays des Contes de Fées",
        "Les Voyages de Pinocchio",
        "Liberty Arcade",
        "Mad Hatter's Tea Cups",
        "Main Street Vehicles",
        "Meet Mickey Mouse",
        "Mickey’s PhilharMagic",
        "Orbitron®",
        "Peter Pan's Flight",
        "Phantom Manor",
        "Pirate Galleon",
        "Pirates of the Caribbean",
        "Pirates' Beach",
        "Princess Pavilion",
        "Rustler Roundup Shootin' Gallery",
        "Sleeping Beauty Castle",
        "Star Tours: The Adventures Continue*",
        "Star Wars Hyperspace Mountain",
        "Thunder Mesa Riverboat Landing",
        "Welcome to Starport: A Star Wars Encounter"
      ]
    }
  }
};
