const exampleModule = {
  module: "MMM-DisneyWaitTimes",
  header: "Magic Kingdom - Tokyo Disney",
  position: "top_left",
  config: {
    park: {
      name: "Magic Kingdom - Tokyo Disney",
      rides: [
        "Alice's Tea Party",
        "Beaver Brothers Explorer Canoes",
        "Big Thunder Mountain",
        "Buzz Lightyear's Astro Blasters",
        "Castle Carrousel",
        "Chip 'n Dale's Treehouse",
        "Cinderella's Fairy Tale Hall",
        "Country Bear Theater",
        "Donald's Boat",
        "Dumbo The Flying Elephant",
        "Enchanted Tale of Beauty and the Beast",
        "Gadget's Go Coaster",
        "Goofy's Paint 'n' Play House",
        "Haunted Mansion",
        "it's a small world",
        "Jungle Cruise: Wildlife Expeditions",
        "Mark Twain Riverboat",
        "Mickey's PhilharMagic",
        "Minnie's House",
        "Monsters, Inc. Ride & Go Seek!",
        "Omnibus",
        "Penny Arcade",
        "Peter Pan's Flight",
        "Pinocchio's Daring Journey",
        "Pirates of the Caribbean",
        "Pooh's Hunny Hunt",
        "Roger Rabbit's Car Toon Spin",
        "Snow White's Adventures",
        "Space Mountain",
        "Splash Mountain",
        "Star Tours: The Adventures Continue",
        "Stitch Encounter",
        "Swiss Family Treehouse",
        "The Enchanted Tiki Room: Stitch Presents “Aloha E Komo Mai!”",
        "The Happy Ride with Baymax",
        "Tom Sawyer Island Rafts",
        "Toon Park",
        "Western River Railroad",
        "Westernland Shootin' Gallery"
      ]
    }
  }
};
